<?php


namespace Claassenmarius\LaravelSkynet\Tests\Unit;

use Claassenmarius\LaravelSkynet\Skynet;
use Claassenmarius\LaravelSkynet\Tests\TestCase;
use Illuminate\Http\Client\RequestException;
use Illuminate\Support\Facades\Http;

class SkynetTest extends TestCase
{
    public Skynet $skynet;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->skynet = $this->app->make(Skynet::class);
    }

    /** @test */
    public function it_can_get_a_security_token()
    {
        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' =>
                Http::response(
                    "{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}",
                    200,
                    ['Content-Type' => 'application/json; charset=utf-8']
                ),
            ]
        );

        $response = $this->skynet->securityToken();

        $this->assertEquals("{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}", $response->body());
    }

    /** @test */
    public function it_can_validate_suburb_and_postcode_combination()
    {
        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' =>
                Http::response(
                    true,
                    200,
                    ['Content-Type' => 'application/json; charset=utf-8']
                ),
            ]
        );

        $response = $this->skynet->validateSuburbAndPostalCode([
            'suburb' => 'Brackenfell',
            'postal-code' => '7560',
        ]);

        $this->assertEquals(true, $response->body());
    }

    /** @test */
    public function it_can_get_postal_codes_for_a_suburb()
    {
        $expectedResponse = '[
                                {
                                    "postalCodeId": 27293,
                                    "suburb": "SWAKOPMUND",
                                    "town": "International",
                                    "province": "International",
                                    "country": "NAMIBIA (OUTLYING)",
                                    "postalCode": "NAMO",
                                    "countryId": 189,
                                    "startDate": "2020-01-01T00:00:00",
                                    "endDate": "9999-12-31T00:00:00",
                                    "isActive": true,
                                    "combined": "SWAKOPMUND, International, International, NAMO"
                                }
                            ]';

        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' => Http::sequence()
                ->push("{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}", 200, ['Content-Type' => 'application/json; charset=utf-8'])
                ->push($expectedResponse, 200, ['Content-Type' => 'application/json; charset=utf-8']),
            ]
        );

        $response = $this->skynet->postalCodesFromSuburb('Swakopmund');

        $this->assertEquals($expectedResponse, $response->body());
    }

    /** @test */
    public function it_can_get_a_quote()
    {
        $expectedResponse = '{
                                "vat": "558.81",
                                "charges": "3725.38",
                                "errorDescription": "",
                                "errorCode": "0"
                            }';
        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' => Http::sequence()
                ->push("{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}", 200, ['Content-Type' => 'application/json; charset=utf-8'])
                ->push($expectedResponse, 200, ['Content-Type' => 'application/json; charset=utf-8']),
            ]
        );

        $response = $this->skynet->quote([
            'collect-city' => 'Brackenfell',
            'deliver-city' => 'Stellenbosch',
            'service-type' => 'DDV',
            'insurance-type' => '1',
            'parcel-insurance' => '0',
            'deliver-postcode' => '7600',
            'parcel-length' => 70,
            'parcel-width' => 80,
            'parcel-height' => 90,
            'parcel-weight' => 60,
        ]);

        $this->assertEquals($expectedResponse, $response->body());
    }

    /** @test */
    public function it_can_get_an_ETA_between_two_locations()
    {
        $expectedResponse = '{
                                "errorDescription": "",
                                "errorCode": 0,
                                "FromBranch": "CPT",
                                "FromClassification": "L2",
                                "responsibleFromBranch": "CPT",
                                "responsibleFromBranchCity": "CAPE TOWN",
                                "responsibleFromBranchCountry": "SOUTH AFRICA",
                                "FromRouting": "BR6",
                                "ToBranch": "CPT",
                                "ToClassification": "L3",
                                "responsibleToBranch": "CPT",
                                "responsibleToBranchCity": "STELLENBOSCH",
                                "responsibleToBranchCountry": "SOUTH AFRICA",
                                "ToRouting": "STEL",
                                "skyQWaybillETAs": [
                                    {
                                        "estimatedDeliveryDate": "23/6/2021 13:00:00",
                                        "serviceType": "ON1"
                                    }
                                ]
                            }';

        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' => Http::sequence()
                ->push("{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}", 200, ['Content-Type' => 'application/json; charset=utf-8'])
                ->push($expectedResponse, 200, ['Content-Type' => 'application/json; charset=utf-8']),
            ]
        );

        $response = $this->skynet->deliveryETA([
            'from-suburb' => 'Brackenfell',
            'from-postcode' => '7560',
            'to-suburb' => 'Stellenbosch',
            'to-postcode' => '7600',
            'service-type' => 'ON1',
        ]);

        $this->assertEquals($expectedResponse, $response->body());
    }

    /** @test */
    public function it_can_create_a_waybill()
    {
        $expectedResponse = '{
                                "errorDescription": "",
                                "errorCode": 0,
                                "waybillNumber": "080900028413",
                                "collectionReferenceNumber": null
                            }';

        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' => Http::sequence()
                ->push("{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}", 200, ['Content-Type' => 'application/json; charset=utf-8'])
                ->push($expectedResponse, 200, ['Content-Type' => 'application/json; charset=utf-8']),
            ]
        );

        $response = $this->skynet->createWaybill([
            "customer-reference" => "Customer Reference",
            "GenerateWaybillNumber" => true,
            "service-type" => "DDV",
            "collection-date" => "2021-06-26",
            "from-address-1" => "3 Janie Street, Ferndale, Brackenfell",
            "from-suburb" => "Brackenfell",
            "from-postcode" => "7560",
            "to-address-1" => "15 Verreweide Street, Universiteitsoord, Stellenbosch",
            "to-suburb" => "Stellenbosch",
            "to-postcode" => "7600",
            "insurance-type" => "1",
            "insurance-amount" => "0",
            "security" => "N",
            "parcel-number" => "1",
            "parcel-length" => 10,
            "parcel-width" => 20,
            "parcel-height" => 30,
            "parcel-weight" => 10,
            "parcel-reference" => "12345",
            "offsite-collection" => true,
        ]);

        $this->assertEquals($expectedResponse, $response->body());
    }

    /** @test */
    public function it_can_return_a_waybill_POD_image()
    {
        $expectedResponse = '{
                                "image": null,
                                "imageType": "pdf",
                                "errorDescription": "Success",
                                "errorCode": 0
                            }';

        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' => Http::sequence()
                ->push("{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}", 200, ['Content-Type' => 'application/json; charset=utf-8'])
                ->push($expectedResponse, 200, ['Content-Type' => 'application/json; charset=utf-8']),
            ]
        );

        $response = $this->skynet->waybillPOD('080900028436');

        $this->assertEquals($expectedResponse, $response->body());
    }

    /** @test */
    public function it_can_return_tracking_information_for_a_waybill()
    {
        $expectedResponse = '[
                                {
                                    "WaybillNumber": "080900028413",
                                    "ReferenceList": [
                                        "CUSTOMERREFERENCE"
                                    ],
                                    "TrackingInfo": [
                                        {
                                            "WaybillEventDate": "22/06/2021",
                                            "WaybillEventTime": "15:51:02",
                                            "WaybillEventDescription": "Created waybill",
                                            "WaybillEventBranch": "HostServer",
                                            "WaybillEventId": 148593792
                                        }
                                    ],
                                    "PODDetails": []
                                }
                            ]';

        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' => Http::sequence()
                ->push($expectedResponse, 200, ['Content-Type' => 'application/json; charset=utf-8']),
            ]
        );

        $response = $this->skynet->trackWaybill('080900028413');

        $this->assertEquals($expectedResponse, $response->body());
    }

    /** @test */
    public function it_throws_a_request_exception()
    {
        Http::fake(
            ['https://api.skynet.co.za:3227/api/*' =>
                Http::response(
                    "{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}",
                    500,
                    ['Content-Type' => 'application/json; charset=utf-8']
                ),
            ]
        );

        $response = $this->skynet->securityToken();

        $this->expectException(RequestException::class);

        if ($response->failed()) {
            $response->throw();
        }

        $this->assertEquals("{\"SecurityToken\":\"2_03ce4988-43db-45ea-9797-e69befff8d3f\"}", $response->body());
    }
}
